### ISSUE TITLE
instantiate method

### ISSUE THREAD

**Issue by fedenusy** [awslabs/aws-sdk-ruby-record#15]
While working with `aws-record` I found it extremely helpful to define an `instantiate` method:

```
# @param [Hash] attrs
#
# @return [Aws::Record]
def instantiate(attrs)
  record = new
  data = record.instance_variable_get('@data')
  attrs_for_extraction = attrs.with_indifferent_access

  attributes.each do |name, attr|
    data[name] = attr.extract(attrs_for_extraction)
  end

  record
end
```

Very similar to `_build_items_from_response` in `item_collection.rb`.

Whenever I work with the low-level `dynamodb_client`, I end up using `MyRecord.instantiate` to build records from the response.

Would be nice to have an officially maintained method like `instantiate` as part of the public API.

**Comment by awood45** [comment]
I'm actually looking at overloading `#initialize` with this behavior. Would take a PR for this, otherwise it's on my roadmap before GA.

**Comment by fedenusy** [comment]
That also makes sense. I have no problem waiting for GA, feel free to close :)

**Comment by awood45** [comment]
I'll leave this open at least in part to encourage a PR for this, if someone would like to do that. Thanks for bringing this up!

**Comment by awood45** [comment]
Done, going out in next release.
