### ISSUE TITLE
Survey/Question: Add a lightweight, optional validation module?

### ISSUE THREAD

**Issue by awood45** [awslabs/aws-sdk-ruby-record#18]
Version `1.0.0.pre.7` removed the built-in `#valid?` and `#errors` methods, directing you to validation libraries like `ActiveModel::Validations` instead. A question to active followers/users: Does anybody find this to be a difficult approach to work with?

ActiveModel provides a rich set of validations, and re-implementing them seems to be wasteful. Some will also enjoy keeping the library lightweight, by not always requiring ActiveModel if not needed for your use case. However, I do see a potential middle ground - does anybody need some validation functionality, but can't or won't use an outside library?

I want to hear about those use cases, if they exist. And if they do, I'm open to ideas for what you would need in an *optional* module that provides validation hooks.

**Comment by mmcfarland-cavulus** [comment]
I feel like the ```#valid?``` interface provides a nice, lightweight insertion point for custom validation. Data validation is a fairly common thing, Dynamo is a pretty flexible datastore, so why not leave that option open?

As an aside, it looks like the existing remnant of ```valid?``` is a class method. This doesn't appear to allow any access to the row data -- I'd imagine it would be used like so:

```ruby
def valid?
  some_validation(@data)
end
```
Does this make sense? Or am I misunderstanding how it's intended to be used?
