### ISSUE TITLE
Survey/Question: Are you using TableMigration? How?

### ISSUE THREAD

**Issue by awood45** [awslabs/aws-sdk-ruby-record#19]
I've gotten some feedback about the `Aws::Record::TableMigration` class. Along those lines, I'm working on enhancements to that library. I'd like to hear what is and is not going well with that class from any current users.

Alternatively, if you're only integrating with existing DynamoDB tables, are the model classes giving you all the functionality you need to do this? If not, where is it falling short?

**Comment by fedenusy** [comment]
Whenever I deploy, I run a script that creates missing tables + indexes for each of my `Aws::Record` classes.

My experience writing the script went OK. I had a hard time understanding the expected format for the `:global_secondary_index_throughput` option, but besides that, everything went smoothly.

I wish the script had been easier to write though. Maybe something along these lines:

```
# initializer.rb
Aws::Record.default_throughput = {
  read_capacity_units: 5,
  write_capacity_units: 2
}

# deploy_hook.rb
AwsRecordClass.ensure_table_exists(options)
# or not have to do anything, and have aws-record create the table upon my first interaction

AwsRecordClass.ensure_indexes_exist(options)
# or not have to do anything, and have aws-record create each index upon my first interaction
```

In the future I also plan to run a cron job that auto-scales throughput for each of my tables + indexes based on recent usage. AFAIK that will require interacting with CloudWatch, which may be outside the scope of this gem.

**Comment by awood45** [comment]
Good feedback! Direct CloudWatch integration may be out of scope for this gem, but maybe not. I think it depends on what the code necessary to do it with `Aws::CloudWatch::Client` looks like. Could be a guide, could be an optional module of some sort.

**Comment by fedenusy** [comment]
Ok, then I'll see if it makes sense to generalize my auto-scale solution. If it does, I'll submit a PR.

**Comment by fedenusy** [comment]
Just to close the loop -- I ended up going with [Dynamic DynamoDB](https://github.com/sebdah/dynamic-dynamodb). It works very well.
