### ISSUE TITLE
Convert Date/Time to utc and iso8601 string when using datetime_attr

### ISSUE THREAD

**Issue by lucleray** [awslabs/aws-sdk-ruby-record#21]
I've used the `datetime_attr` of aws-record, but since this type is not available in DynamoDB, it is converted to a string.

Yet, it is not really convenient to store dates without any convention in DynamoDB because I want to sort by date. Is it possible to convert date/time to utc and iso8601 before storing them in DynamoDB, or to create a new type of attributes to do so (something like `utc_time_attr`) ?

It is really easy to convert to this format using Ruby :
```ruby
Time.parse(my_date).utc.iso8601
```

Something like this could work :
```ruby
require 'time'

module UtcTimeMarshaler
  def self.type_cast(raw_value, options = {})
    case raw_value
    when nil
      nil
    when ''
      nil
    when Integer
      Time.at(raw_value).utc.iso8601
    when Time
      raw_value.utc.iso8601
    when DateTime
      raw_value.to_time.utc.iso8601
    else
      Time.parse(raw_value.to_s).utc.iso8601
    end
  end

  def self.serialize(raw_value, options = {})
    time = type_cast(raw_value)
    case time
    when nil
      nil
    when Time
      time.utc.iso8601
    else
      msg = "expected a DateTime value or nil, got #{datetime.class}"
      raise ArgumentError, msg
    end
  end
end
```

**Comment by awood45** [comment]
I can say that we're looking in to the best way for Date(Time) types to support different time formats (especially for compatibility reasons.

Notably, as a workaround, you can create attributes right now using your marshaler:

```ruby
class Model
  include Aws::Record
  string_attr :key, hash_key: true
  attr :utc_date, UtcTimeMarshaler
end
```

The generic `#attr` method was designed with this type of use case in mind. That said, I'm definitely looking at ways to avoid that for date support.

**Comment by awood45** [comment]
As far as the UTC standard goes, one thing I want to be cautious about is ensuring that existing formats in DDB can be supported. UTC by default is a good idea and will happen, but if you happen to store things in your local time zone, not the persistence layer's place to judge.

**Comment by lucleray** [comment]
I'm using this UTC Marshaller as a temporary fix before DDB implements Dates and Time. It's probably better to store the timezone too, but if I do this now, I won't be able to sort my data with a DDB Index.

So as far as I know, UTC is the only solution I have (or I could store dates in an other timezone, but it adds more complexity to my code).

**Comment by awood45** [comment]
As long as you're consistent in the time zone used for storage, the existing DateTime class is string sortable in cases that I've tried. Have you found that to be untrue? (Really asking, in case it's an implementation issue.)

**Comment by lucleray** [comment]
It is working ! I would just prefer to sort them in UTC Timezone, so I just configure every server accessing the DDB with UTC, and there is no consistency settings for date and times :)

**Comment by awood45** [comment]
#29 addresses this in a more permanent way.

While we already used an ISO8601 compliant string format, this provides a pluggable way to bring your own format, and for us to support more format types down the road.

It also makes UTC conversion the default, while allowing you to use local time instead if you wish to handle time zone settings (not recommended, but the persistence layer is not here to judge that decision).

**Comment by steveclarkin** [comment]
I was wondering if something could point me to or provide an example on how to use a custom formatter for datetime_attr? I would like to store datetime in DynamoDB to millisecond resolution. ie. "2017-09-10T06:32:53.484Z"

I understand that this should still work as a range key and BETWEEN should work when querying for rows between two datetimes of millisecond resolution?
