### ISSUE TITLE
New TableMigration with local DynamoDB instance returns NoMethodError

### ISSUE THREAD

**Issue by mmcfarland-cavulus** [awslabs/aws-sdk-ruby-record#23]
I'm having trouble creating migrations with a local version of DynamoDB. I'm supplying TableMigration with a client that (tested successfully) connects to the local DynamoDB instance, and am using valid AWS credentials, like so:

```ruby
client = Aws::DynamoDB::Client.new(
  region: 'localhost', 
  endpoint: 'http://localhost:8000', 
  access_key_id: 'goodkey', 
  secret_access_key: 'validsecret')
migration = Aws::Record::TableMigration.new(MyModel, opts: {:client => client})
```

I've also tried it with a valid AWS region (ie ```us-west-1```). The error I receive in each instance is:

```java
NoMethodError: undefined method `match' for nil:NilClass
  block in partition_matching_region at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:67
                                find at org/jruby/RubyEnumerable.java:633
           partition_matching_region at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:66
                       get_partition at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:54
                        endpoint_for at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:26
                             resolve at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:10
                             resolve at aws-sdk-core-2.3.8/lib/aws-sdk-core/endpoint_provider.rb:80
           block in RegionalEndpoint at aws-sdk-core-2.3.8/lib/aws-sdk-core/plugins/regional_endpoint.rb:24
                                call at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:64
           block in resolve_defaults at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:199
                                each at org/jruby/RubyArray.java:1593
                                each at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:57
                    resolve_defaults at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:198
                            value_at at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:194
                    block in resolve at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:183
                            each_key at org/jruby/RubyHash.java:1511
                                each at lib/ruby/stdlib/set.rb:306
                             resolve at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:183
                      apply_defaults at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:171
                              build! at aws-sdk-core-2.3.8/lib/seahorse/client/configuration.rb:144
                        build_config at aws-sdk-core-2.3.8/lib/seahorse/client/base.rb:68
                          initialize at aws-sdk-core-2.3.8/lib/seahorse/client/base.rb:19
                                 new at aws-sdk-core-2.3.8/lib/seahorse/client/base.rb:105
                          initialize at aws-record-1.0.0.pre.8/lib/aws-record/record/table_migration.rb:34
```

As you can see, I'm using JRuby, but as the library is the same it seems unlikely that this is the problem. Any thoughts? Am I setting up the local table migration correctly?

**Comment by awood45** [comment]
It's not a helpful error message from the SDK, but you're not setting the migration up correctly. `opts` is not a named parameter or a hash key, it's the name of the hash variable itself. So you're passing in `MyModel` for the `model` param, and `{ opts: { client: client }}` for `opts`. Thus the `:client` key in opts is returning `nil`, and we attempt to construct a new client. My guess is you don't have a default region specified, and it's barfing in JRuby in that manner.

First, let's try the following modification to your earlier example:

```ruby
client = Aws::DynamoDB::Client.new(
  region: 'localhost', 
  endpoint: 'http://localhost:8000', 
  access_key_id: 'goodkey', 
  secret_access_key: 'validsecret')
migration = Aws::Record::TableMigration.new(MyModel, {:client => client})
```

Let's see if that gets you unstuck.

**Comment by awood45** [comment]
Aside from the `aws-record` question, I'm having trouble replicating the stack trace you're seeing.

Can you tell me exactly what you ran to get the above stack trace?

**Comment by mmcfarland-cavulus** [comment]
That seems to have done it. Many thanks!

So far as my command goes:

```
jruby -I src src/do_setup.rb
```

Gemfile contains this library and aws-sdk ~> 2. Also, running this from w/in RVM.

**Comment by mmcfarland-cavulus** [comment]
It looks like the signature mis-interpretation was the root of the problem -- I'm going to close this issue, but can feed you more details of my setup if you need them.

**Comment by awood45** [comment]
Glad to hear you're unstuck!

I was mainly curious about what command you were running that caused that particular stack trace. That's an investigation of if there is an issue with the `aws-sdk` gem.

**Comment by vivek2007** [comment]
rake aborted!
NoMethodError: undefined method `match' for nil:NilClass
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:70:in `call'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:70:in `call'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:57:in `each'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:57:in `each'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:200:in `value_at'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:189:in `block in resolve'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:189:in `resolve'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/configuration.rb:150:in `build!'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:68:in `build_config'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:19:in `initialize'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:105:in `new'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/resource.rb:169:in `extract_client'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/resource.rb:15:in `initialize'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/refile-s3-0.2.0/lib/refile/s3.rb:45:in `new'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/refile-s3-0.2.0/lib/refile/s3.rb:45:in `initialize'
/home/vivek/Documents/startuplegal/config/initializers/refile.rb:10:in `new'
/home/vivek/Documents/startuplegal/config/initializers/refile.rb:10:in `<top (required)>'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/home/vivek/Documents/startuplegal/config/environment.rb:5:in `<top (required)>'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/airbrake-5.2.2/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/vivek/.rvm/gems/ruby-2.2.3/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/vivek/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/vivek/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by vivek2007** [comment]
@awood45 I am facing above issue please solve that

**Comment by awood45** [comment]
You're seeing that because you have not specified a region, so client construction is failing. Newer versions of the `aws-sdk-core` gem show a more user-friendly error in this scenario.

To solve this, you have a couple options. First, you can run with the `AWS_REGION` environment variable set to the region you wish to create your table in. Second, you can set the region in a custom client that you provide to the table migration script:

```ruby
client = Aws::DynamoDB::Client.new(region: REGION)
migration = Aws::Record::TableMigration.new(MyModel, client: client)
# Perform migration operations.
```

**Comment by awood45** [comment]
There is a third option with newer versions of the `aws-sdk-core` gem, which is to set a default region in the shared credentials or shared configuration file for the profile you're using.

**Comment by vivek2007** [comment]
@awood45 newer version means i need to mention the gem version in gem file ?

**Comment by vivek2007** [comment]
aws-sdk (2.3.22)
      aws-sdk-resources (= 2.3.22)
    aws-sdk-core (2.3.22)

**Comment by awood45** [comment]
So, the problem is the same no matter what your gem version is - you need to configure a region. If you want to use `aws-sdk` version `2.5.0` or greater, you can use the shared credential or shared configuration files. But you do not need to upgrade your gem to fix the issue.

Just set the `AWS_REGION` environment variable to the region you wish to use, or create and pass in a custom client to the table migration object (and to the table itself, for table ops).
