### ISSUE TITLE
before / after callbacks

### ISSUE THREAD

**Issue by arktisklada** [awslabs/aws-sdk-ruby-record#6]
Thanks for putting this out, it's great!  One thing I could see helping are some before/after save/update/etc. callbacks.  I'm going to start working on something, and wanted to be sure it wasn't in progress.  Let me know!

**Comment by awood45** [comment]
No plans at this point - I'm open to looking at a pull request. There are a few considerations that are worth discussing:

## Callbacks are supported now, in a way.

Consider the following code:

```ruby
class MyModel
  include Aws::Record

  # Define attributes here.

  def save
    # Do "before" stuff.
    super
    # Do "after" stuff.
  end
end
```

You can wrap any method you like with callbacks in this manner. It's not the same pattern, but it works in essentially the same way.

One shortcoming of this is that we haven't divided out calls that hit `#put_item` and `#update_item`, yet. That is coming up soon, so you'd be able to wrap different methods to cover different lifecycle events.

If callbacks are going to provide compelling functionality that this doesn't, let me know so we can consider that.

## No New Dependencies

We're doing everything we can to avoid extra dependencies. Unless there is a critical reason, we're not taking pull requests that add dependencies, including gems like `ActiveSupport`.

**Comment by arktisklada** [comment]
Gotcha, I see what you're getting at.  And :+1: to no added dependencies.  It'll be nice to keep this slim and able to operate without any external code influences.

I think my idea came from seeing this implementation, and mentally relating it to the [Mongoid](https://github.com/mongodb/mongo-ruby-driver) gem.  There's a similar `include` style implementation, and the callback style is a design pattern I've become familiar with in the ruby world.  Other than consistency and potential expectations, I don't have any other arguments at this time.

**Comment by awood45** [comment]
Understood. If you think that there's a case for callbacks, an example of a problem this doesn't handle well, but callbacks will, could be helpful.

To be clear, I'm not saying "no callbacks" firmly. Just looking for the problem it solves to make sure we solve it in the best way.

**Comment by arktisklada** [comment]
Update: my thinking about other ORMs in the ruby language and `before_save`, `after_save` handlers could help with ease of transition to DynamoDB from existing systems.  I'll let you know if I come across a situation where overloading the `save`, etc. method doesn't accomplish the same thing.

**Comment by awood45** [comment]
In that case, I'd look at it as a possible optional module. For example, it would be written such that you could create a model thusly:

```ruby
class MyModel
  include Aws::Record
  include Aws::Record::Callbacks
  # Other code + callback definitions
end
```

I'd take a PR for that, since an optional module seems like the correct approach for convenience layers.

**Comment by awood45** [comment]
I'm going to close this out since it's not really on our roadmap until we understand the need a bit better. Doesn't mean that I won't take a PR that provides this as an optionally included module, however.

**Comment by metaskills** [comment]
A few possible downsides to re-implementing #save for ad-hoc callbacks.

* Would require users consider the arity of the method or use `*args` to avoid conflicts.
* It would be nice to only fire the callback before/after `_perform_save` since the `save` method does an internal check for `_invalid_record?`
* Callbacks keep users from knowing how things are implemented which could change. 

All that said, I'll be trying to use the `#save` override and super method.
